config/routes.rb
Rails.application.routes.draw do
  get "weather/index"
  post "weather/search", to: "weather#search", as: "search_weather"
  get "weather/:zip", to: "weather#show", as: "show_weather"

  root "weather#index"
end

app/models/address.rb
Address = Struct.new(:zip)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
Forecast = Struct.new(:high, :low, :temperature, :date)

app/models/result.rb
class Result
  attr_reader :value, :errors
  def initialize(value, errors = nil)
    @value = value
    @errors = errors
  end

  def errors?
    !errors.nil?
  end

  def self.success(value)
    new(value)
  end

  def self.fail(error)
    new(nil, error)
  end
end

app/models/weather_result.rb
WeatherResult = Struct.new(:city, :current_forecast, :extended_forecast, :cached)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController


  def index
  end

  def show
    result = FetchForecast.for(params[:zip])
    if result.errors?
      redirect_to root_path, alert: result.errors
    else
      @weather = result.value
    end
  end

  def search
    result = AddressValidator.validate(params[:location])
    if result.errors?
      redirect_to root_path, alert: result.errors
    else
      redirect_to show_weather_path(result.value.zip)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherStation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/weather/index.html.erb
<div class="flex flex-col w-full place-content-center">
  <h1 class="justify-center font-bold text-4xl text-center"><%= t(:app_title) %></h1>
  <%- if flash[:alert] %>
    <div class="m-auto bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <p><%= t(flash[:alert]) %></p>
    </div>
  <% end %>
  <div class="m-auto">
    <%= form_with url: search_weather_path, method: :post do |form| %>
      <%= form.text_field :location, class: "mt-2 p-2 border border-gray-300 rounded focus:border-blue-500 focus:outline-none", placeholder: t(:input_placeholder_prompt), required: true %>
      <%= form.submit t(:get_weather), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    <% end %>
  </div>
</div>

app/views/weather/show.html.erb
<div class="mx-auto">
  <div class="max-w-md p-8 mx-auto rounded-lg bg-gray-900 text-gray-100">
    <div class="flex justify-between space-x-8">
      <div class="flex flex-col text-left">
        <h1 class="text-xl font-semibold"><%= @weather.city %></h1>
        <p class="text-slate-500 text-sm">high: <%= @weather.current_forecast.high %>°</p>
        <p class="text-slate-500 text-sm">low: <%= @weather.current_forecast.low %>°</p>
        <%- if @weather.cached %>
          <p class="text-slate-500 text-sm border border-slate-500 rounded text-center p-1 mt-1"><%= t(:cached) %></p>
        <% end %>
      </div>
      <span class="font-bold text-8xl"><%= @weather.current_forecast.temperature %>°</span>
    </div>
    <div class="flex justify-between mt-8 space-x-4 text-slate-500">
      <%- @weather.extended_forecast.each do |forecast| %>
        <div class="flex flex-col items-center space-y-1">
          <span class="uppercase"><%= forecast.date.strftime('%a') %></span>
          <span><%= forecast.temperature %>°</span>
        </div>
      <% end %>
    </div>
  </div>

  <a href="/" class="text-blue-400 hover:text-blue-600 text-center"><%= t(:search_for_new_location) %></a>
</div>